language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.1.x
  - PLONE=4.1.x-contenttree
  - PLONE=4.2.x
  - PLONE=4.3.x
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.0.x
    - python: 2.7
      env: PLONE=4.1.x
    - python: 2.6
      env: PLONE=4.2.x
    - python: 2.6
      env: PLONE=4.3.x
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis-$PLONE.cfg
  - bin/buildout -N -t 5 -c travis-$PLONE.cfg
script: bin/test
